import { AppProps } from 'next/app';
import Head from 'next/head';
import '../styles/globals.scss';


function MyApp({ Component, pageProps }: AppProps): JSX.Element {
	return <>
		<Head>
			<title>Inviglab admin panel</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
		</Head>
		<Component {...pageProps} />
	</>;
}
export default MyApp;
